BEGIN;

ALTER TABLE users ADD COLUMN username VARCHAR(255);
ALTER TABLE users ADD COLUMN first_name VARCHAR(255);
ALTER TABLE users ADD COLUMN last_name VARCHAR(255);
ALTER TABLE users ADD COLUMN language_code VARCHAR(255) DEFAULT 'en' NOT NULL;
ALTER TABLE users ADD COLUMN is_bot BOOLEAN DEFAULT FALSE NOT NULL;

COMMIT;